### ISSUE TITLE
Get install script to build needed archives under centos

### ISSUE THREAD

**Issue by gdey** [go-spatial/go-mbgl#28]
Currently, snap will not build in CentOs and the install.sh script is particular to Ubuntu. Port over the install to script to allow it to build the need archives.

**Comment by jj0hns0n** [comment]
I think building on Ubuntu is still okay as I'm already running the binary
on centos

**Comment by ARolek** [comment]
@jj0hns0n the main reason for this issue is bringing together go-mbgl and go-rsvg together to support maptoolkit. We need to have both built for the same target OS.

**Comment by jj0hns0n** [comment]
Whatever works, but as long as it _runs_ on centos, it doesnt necessarily
matter where its built.

**Comment by ARolek** [comment]
Absolutely.
